/**
 * sync-vendor.mjs —— 把 packages/core 同步进 packages/mcp/vendor-core/。
 *
 * mcp-wiki 以 npm 单包分发且需自包含（宿主按绝对路径直接 node 运行 bin，不解析
 * file:/npm 依赖）。core 作为 vendor 打进包，lib/core.mjs 优先同包 vendor-core。
 *
 * 用法：node packages/mcp/scripts/sync-vendor.mjs
 */

import { readdir, copyFile, mkdir, writeFile, readFile } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const mcpRoot = join(here, '..')
const coreRoot = join(mcpRoot, '..', 'core')
const vendor = join(mcpRoot, 'vendor-core')

await mkdir(join(vendor, 'lib'), { recursive: true })

// index.mjs + lib/*.mjs
await copyFile(join(coreRoot, 'index.mjs'), join(vendor, 'index.mjs'))
const libFiles = (await readdir(join(coreRoot, 'lib'))).filter((f) => f.endsWith('.mjs'))
for (const f of libFiles) {
  await copyFile(join(coreRoot, 'lib', f), join(vendor, 'lib', f))
}

// vendor package.json（供 import 语义，实际是目录直引）
const corePkg = JSON.parse(await readFile(join(coreRoot, 'package.json'), 'utf8'))
await writeFile(
  join(vendor, 'package.json'),
  JSON.stringify(
    {
      name: '@sidleo3/llm-wiki-core-vendor',
      version: corePkg.version,
      description: '@sidleo3/llm-wiki-core vendored into mcp-wiki (auto-generated by sync-vendor.mjs; do not edit)',
      type: 'module',
      main: 'index.mjs',
    },
    null,
    2,
  ) + '\n',
)

console.log(`vendor-core 已同步（${libFiles.length} lib 文件 + index.mjs），version ${corePkg.version}`)
