/**
 * sync-vendor.mjs —— 把 packages/core 同步进 packages/dsh/vendor-core/。
 *
 * dsh-wiki 以 npm 单包分发且需自包含（DSH profile 安装是 pnpm link 本地目录，
 * 不解析 file:/npm 依赖）。core 作为 vendor 打进包，wiki.mjs loadCore 优先
 * 同包 vendor-core。
 *
 * 用法：node packages/dsh/scripts/sync-vendor.mjs
 */

import { readdir, copyFile, mkdir, writeFile, readFile } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const dshRoot = join(here, '..')
const coreRoot = join(dshRoot, '..', 'core')
const vendor = join(dshRoot, 'vendor-core')

await mkdir(join(vendor, 'lib'), { recursive: true })

// index.mjs + lib/*.mjs
await copyFile(join(coreRoot, 'index.mjs'), join(vendor, 'index.mjs'))
const libFiles = (await readdir(join(coreRoot, 'lib'))).filter((f) => f.endsWith('.mjs'))
for (const f of libFiles) {
  await copyFile(join(coreRoot, 'lib', f), join(vendor, 'lib', f))
}

// vendor package.json（供 import 语义，实际是目录直引）
const corePkg = JSON.parse(await readFile(join(coreRoot, 'package.json'), 'utf8'))
await writeFile(
  join(vendor, 'package.json'),
  JSON.stringify(
    {
      name: 'llm-wiki-core-vendor',
      version: corePkg.version,
      description: 'llm-wiki-core vendored into dsh-wiki (auto-generated by sync-vendor.mjs; do not edit)',
      type: 'module',
      main: 'index.mjs',
    },
    null,
    2,
  ) + '\n',
)

console.log(`vendor-core 已同步（${libFiles.length} lib 文件 + index.mjs），version ${corePkg.version}`)
